name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]

# jobs:
#   unit-tests:
#     name: Run Unit Tests & Terraform Validate
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v4
#
#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: 16
#
#       - name: Install Node Dependencies
#         run: npm install
#
#       - name: Run Unit Tests
#         run: npm run test
#
#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v2
#
#       - name: Terraform Init & Validate
#         working-directory: ./terraform
#         run: |
#           terraform init
#           terraform validate

jobs:
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init & Validate (Staging)
        working-directory: ./terraform
        run: |
          terraform init
          terraform validate

      - name: Terraform Plan (Staging)
        working-directory: ./terraform
        run: |
          terraform plan -var="environment=staging" -var-file=staging.tfvars -out=staging.tfplan
          terraform show -no-color staging.tfplan > staging-plan.txt

      - name: Upload Staging Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: staging-tfplan
          path: ./terraform/staging-plan.txt

      - name: Terraform Apply (Staging)
        working-directory: ./terraform
        run: terraform apply -auto-approve staging.tfplan

  deploy-prod:
    name: Deploy to Production
    needs: [ deploy-staging ]
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init & Validate (Production)
        working-directory: ./terraform
        run: |
          terraform init
          terraform validate

      - name: Terraform Plan (Production)
        working-directory: ./terraform
        run: |
          terraform plan -var="environment=production" -var-file=production.tfvars -out=production.tfplan
          terraform show -no-color production.tfplan > production-plan.txt

      - name: Upload Production Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: production-tfplan
          path: ./terraform/production-plan.txt

      - name: Terraform Apply (Production)
        working-directory: ./terraform
        run: terraform apply -auto-approve production.tfplan
